name: CI

on:
  push:
    branches: main
  pull_request:

env:
  CARGO_TERM_COLOR: always
jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable
      - name: Run rustfmt
        run: cargo fmt --check

  clippy:
      name: Clippy
      runs-on: ubuntu-24.04

      steps:
        - name: Checkout the repository
          uses: actions/checkout@v4
        - name: Update Rust
          run: rustup update stable
        - name: Run clippy
          run: cargo clippy -- --deny warnings

  tests:
    name: Tests
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Update Rust
        run: rustup update stable
      - name: Run tests
        run: cargo test
